services:
  - type: web
    name: voice-ai-server
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: 8081
      - key: SARVAM_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: CEREBRAS_API_KEY
        sync: false
      - key: DEFAULT_PROVIDER
        value: groq
      - key: SARVAM_STT_LANGUAGE_CODE
        value: gu-IN
      - key: TTS_TARGET_LANGUAGE_CODE
        value: hi-IN
      - key: TTS_SPEAKER
        value: shubh
      - key: VOICE_SERVER_LOG_LEVEL
        value: info

  - type: web
    name: voice-ai-frontend
    env: node
    plan: free
    region: oregon
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: VOICE_SERVER_URL
        value: wss://voice-ind.onrender.com/
      - key: NEXT_PUBLIC_VOICE_SERVER_URL
        value: wss://voice-ind.onrender.com/
